name: github-action
env:
  apiKey: "1fa2bd892fe3da05236ef806"
  apiSecret: "cf995a04c7bb53b15187d24ce15da14dfa23d6d2641ce6c1c32fc7b25c9b5791b56ba218"
  testID: "14643428"
  continuePipeline: "false"
  showTailLog: "true"
  totalUsers: "7" 
  duration: "5" 
  rampUp: "2"

  
on: push
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: BlazeRunner-BZR/Github-Action@v8.1
        id: run-test
        with:
          apiKey: ${{env.apiKey}}
          apiSecret: ${{env.apiSecret}}
          testID: ${{env.testID}}
          totalUsers: ${{env.totalUsers}} 
	  duration: ${{env.duration}} 
	  rampUp: ${{env.rampUp}}
          uploadFileCheck: ${{env.uploadFileCheck}}
          inputStartFile: ${{env.inputStartFile}}
          continuePipeline: ${{env.continuePipeline}}
          showTailLog: ${{env.showTailLog}}
